In [1]:
# Imports

library(dslabs)

There will be more going through the motions here. Taking the quadratic formula example:

In [2]:
coef_a <- 1
coef_b <- 1
# Named to avoid conflict with builtin function c()
coef_c <- -1

Very basic printing, which I won't really use in the future because it's Jupyter:

In [3]:
print(coef_a)

[1] 1

In [4]:
print(coef_b)

[1] 1

In [5]:
print(coef_c)

[1] -1

Here's the equivalent of `dir()` (only shows user-defined variables by default):

In [6]:
ls()

[1] "coef_a" "coef_b" "coef_c"

I'm going to do one (or two) better than the book and use a function to calculate the two roots, in addition to making the discriminant a complex number:

In [7]:
quadratic_formula <- function(a, b, c) {
    discriminant <- sqrt(as.complex(b^2 - 4 * a * c))
    r_1 <- (-b - discriminant) / (2 * a)
    r_2 <- (-b + discriminant) / (2 * a)

    list(r_1, r_2)
}

In [8]:
quadratic_formula(coef_a, coef_b, coef_c)

[[1]]
[1] -1.618034+0i

[[2]]
[1] 0.618034+0i

The code above also works with imaginary roots:

In [9]:
quadratic_formula(coef_a, coef_b, 100)

[[1]]
[1] -0.5-9.987492i

[[2]]
[1] -0.5+9.987492i

The book goes into further detail about functions. Note that just evaluating `ls` for example without function application will reveal the source of said function:

In [10]:
ls

function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE,
    pattern, sorted = TRUE)
{
    if (!missing(name)) {
        pos <- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name <- substitute(name)
            if (!is.character(name))
                name <- deparse(name)
            warning(gettextf("%s converted to character string",
                sQuote(name)), domain = NA)
            pos <- name
        }
    }
    all.names <- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll <- length(grep("[", pattern, fixed = TRUE))) &&
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern <- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[<-", pattern))) {
                pattern <- sub("\\[<-", "\\\\\\[<-", pattern)
                warning("replaced '[<-' by '\\\\[<-' in regular expression pattern")
            }
        }
        grep(pattern, all.names, value = TRUE)
    }
    else all.names
}
<bytecode: 0x56345e2007d0>
<environment: namespace:base>

The book covers some more basic info on functions using `log()`:

In [11]:
log(8)

[1] 2.079442

In [12]:
log(coef_a)

[1] 0

And now the help system:

In [13]:
help(log)

log                    package:base                    R Documentation

_L_o_g_a_r_i_t_h_m_s _a_n_d _E_x_p_o_n_e_n_t_i_a_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘log’ computes logarithms, by default natural logarithms, ‘log10’
     computes common (i.e., base 10) logarithms, and ‘log2’ computes
     binary (i.e., base 2) logarithms.  The general form ‘log(x, base)’
     computes logarithms with base ‘base’.

     ‘log1p(x)’ computes log(1+x) accurately also for |x| << 1.

     ‘exp’ computes the exponential function.

     ‘expm1(x)’ computes exp(x) - 1 accurately also for |x| << 1.

_U_s_a_g_e:

     log(x, base = exp(1))
     logb(x, base = exp(1))
     log10(x)
     log2(x)

     log1p(x)

     exp(x)
     expm1(x)

_A_r_g_u_m_e_n_t_s:

       x: a numeric or complex vector.

    base: a positive or complex number: the base with respect to which
          logarithms are computed.  Defaults to e=‘exp(1)’.

_D_e_t_a_i_l_s:

     All except ‘logb’ are generic functions: methods can be defined
     for them individually or via the ‘Math’ group generic.

     ‘log10’ and ‘log2’ are only convenience wrappers, but logs to
     bases 10 and 2 (whether computed _via_ ‘log’ or the wrappers) will
     be computed more efficiently and accurately where supported by the
     OS.  Methods can be set for them individually (and otherwise
     methods for ‘log’ will be used).

     ‘logb’ is a wrapper for ‘log’ for compatibility with S.  If (S3 or
     S4) methods are set for ‘log’ they will be dispatched.  Do not set
     S4 methods on ‘logb’ itself.

     All except ‘log’ are primitive functions.

_V_a_l_u_e:

     A vector of the same length as ‘x’ containing the transformed
     values.  ‘log(0)’ gives ‘-Inf’, and ‘log(x)’ for negative values
     of ‘x’ is ‘NaN’.  ‘exp(-Inf)’ is ‘0’.

     For complex inputs to the log functions, the value is a complex
     number with imaginary part in the range [-pi, pi]: which end of
     the range is used might be platform-specific.

_S_4 _m_e_t_h_o_d_s:

     ‘exp’, ‘expm1’, ‘log’, ‘log10’, ‘log2’ and ‘log1p’ are S4 generic
     and are members of the ‘Math’ group generic.

     Note that this means that the S4 generic for ‘log’ has a signature
     with only one argument, ‘x’, but that ‘base’ can be passed to
     methods (but will not be used for method selection).  On the other
     hand, if you only set a method for the ‘Math’ group generic then
     ‘base’ argument of ‘log’ will be ignored for your class.

_S_o_u_r_c_e:

     ‘log1p’ and ‘expm1’ may be taken from the operating system, but if
     not available there then they are based on the Fortran subroutine
     ‘dlnrel’ by W. Fullerton of Los Alamos Scientific Laboratory (see
     <https://netlib.org/slatec/fnlib/dlnrel.f>) and (for small x) a
     single Newton step for the solution of ‘log1p(y) = x’
     respectively.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.  (for ‘log’, ‘log10’ and
     ‘exp’.)

     Chambers, J. M. (1998) _Programming with Data.  A Guide to the S
     Language_.  Springer. (for ‘logb’.)

_S_e_e _A_l_s_o:

     ‘Trig’, ‘sqrt’, ‘Arithmetic’.

_E_x_a_m_p_l_e_s:

     log(exp(3))
     log10(1e7) # = 7

     x <- 10^-(1+2*1:9)
     cbind(deparse.level=2, # to get nice column names
           x, log(1+x), log1p(x), exp(x)-1, expm1(x))

Notice that `?` typically works as well:

In [14]:
?log

log                    package:base                    R Documentation

_L_o_g_a_r_i_t_h_m_s _a_n_d _E_x_p_o_n_e_n_t_i_a_l_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘log’ computes logarithms, by default natural logarithms, ‘log10’
     computes common (i.e., base 10) logarithms, and ‘log2’ computes
     binary (i.e., base 2) logarithms.  The general form ‘log(x, base)’
     computes logarithms with base ‘base’.

     ‘log1p(x)’ computes log(1+x) accurately also for |x| << 1.

     ‘exp’ computes the exponential function.

     ‘expm1(x)’ computes exp(x) - 1 accurately also for |x| << 1.

_U_s_a_g_e:

     log(x, base = exp(1))
     logb(x, base = exp(1))
     log10(x)
     log2(x)

     log1p(x)

     exp(x)
     expm1(x)

_A_r_g_u_m_e_n_t_s:

       x: a numeric or complex vector.

    base: a positive or complex number: the base with respect to which
          logarithms are computed.  Defaults to e=‘exp(1)’.

_D_e_t_a_i_l_s:

     All except ‘logb’ are generic functions: methods can be defined
     for them individually or via the ‘Math’ group generic.

     ‘log10’ and ‘log2’ are only convenience wrappers, but logs to
     bases 10 and 2 (whether computed _via_ ‘log’ or the wrappers) will
     be computed more efficiently and accurately where supported by the
     OS.  Methods can be set for them individually (and otherwise
     methods for ‘log’ will be used).

     ‘logb’ is a wrapper for ‘log’ for compatibility with S.  If (S3 or
     S4) methods are set for ‘log’ they will be dispatched.  Do not set
     S4 methods on ‘logb’ itself.

     All except ‘log’ are primitive functions.

_V_a_l_u_e:

     A vector of the same length as ‘x’ containing the transformed
     values.  ‘log(0)’ gives ‘-Inf’, and ‘log(x)’ for negative values
     of ‘x’ is ‘NaN’.  ‘exp(-Inf)’ is ‘0’.

     For complex inputs to the log functions, the value is a complex
     number with imaginary part in the range [-pi, pi]: which end of
     the range is used might be platform-specific.

_S_4 _m_e_t_h_o_d_s:

     ‘exp’, ‘expm1’, ‘log’, ‘log10’, ‘log2’ and ‘log1p’ are S4 generic
     and are members of the ‘Math’ group generic.

     Note that this means that the S4 generic for ‘log’ has a signature
     with only one argument, ‘x’, but that ‘base’ can be passed to
     methods (but will not be used for method selection).  On the other
     hand, if you only set a method for the ‘Math’ group generic then
     ‘base’ argument of ‘log’ will be ignored for your class.

_S_o_u_r_c_e:

     ‘log1p’ and ‘expm1’ may be taken from the operating system, but if
     not available there then they are based on the Fortran subroutine
     ‘dlnrel’ by W. Fullerton of Los Alamos Scientific Laboratory (see
     <https://netlib.org/slatec/fnlib/dlnrel.f>) and (for small x) a
     single Newton step for the solution of ‘log1p(y) = x’
     respectively.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.  (for ‘log’, ‘log10’ and
     ‘exp’.)

     Chambers, J. M. (1998) _Programming with Data.  A Guide to the S
     Language_.  Springer. (for ‘logb’.)

_S_e_e _A_l_s_o:

     ‘Trig’, ‘sqrt’, ‘Arithmetic’.

_E_x_a_m_p_l_e_s:

     log(exp(3))
     log10(1e7) # = 7

     x <- 10^-(1+2*1:9)
     cbind(deparse.level=2, # to get nice column names
           x, log(1+x), log1p(x), exp(x)-1, expm1(x))

The book covers `args()` as well, which I didn't know about previously:

In [15]:
args(log)

function (x, base = exp(1))
NULL

`log()` has an optional argument, `base`:

In [16]:
log(8, base=2)

[1] 3

Several other ways of specifying arguments with or without keywords are shown:

In [17]:
log(x = 8, base = 2)

[1] 3

In [18]:
log(8, 2)

[1] 3

In [19]:
# Here the order doesn't even matter because all keywords were specified
log(base = 2, x = 8)

[1] 3

There are exceptions to the rule that functions require parentheses to be evaluated. Among these are the arithmetic operators:

In [20]:
2^3

[1] 8

Note that these and a number of other operators are *indeed* functions:

In [21]:
`^`

function (e1, e2)  .Primitive("^")

The backticks can even be used to apply an operator like `^` as a prefix function like most other functions:

In [22]:
`^`(2, 3)

[1] 8

The book advises that quotes can be used to look up the help info on these operators:

In [23]:
help('^')

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

In [24]:
?'^'

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

It would appear the backticks are also effective:

In [25]:
?`^`

Arithmetic                package:base                 R Documentation

_A_r_i_t_h_m_e_t_i_c _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     These unary and binary operators perform arithmetic on numeric or
     complex vectors (or objects which can be coerced to them).

_U_s_a_g_e:

     + x
     - x
     x + y
     x - y
     x * y
     x / y
     x ^ y
     x %% y
     x %/% y

_A_r_g_u_m_e_n_t_s:

    x, y: numeric or complex vectors or objects which can be coerced to
          such, or other objects for which methods have been written.

_D_e_t_a_i_l_s:

     The unary and binary arithmetic operators are generic functions:
     methods can be written for them individually or via the ‘Ops’
     group generic function.  (See ‘Ops’ for how dispatch is computed.)

     If applied to arrays the result will be an array if this is
     sensible (for example it will not if the recycling rule has been
     invoked).

     Logical vectors will be coerced to integer or numeric vectors,
     ‘FALSE’ having value zero and ‘TRUE’ having value one.

     ‘1 ^ y’ and ‘y ^ 0’ are ‘1’, _always_.  ‘x ^ y’ should also give
     the proper limit result when either (numeric) argument is infinite
     (one of ‘Inf’ or ‘-Inf’).

     Objects such as arrays or time-series can be operated on this way
     provided they are conformable.

     For double arguments, ‘%%’ can be subject to catastrophic loss of
     accuracy if ‘x’ is much larger than ‘y’, and a warning is given if
     this is detected.

     ‘%%’ and ‘x %/% y’ can be used for non-integer ‘y’, e.g. ‘1 %/%
     0.2’, but the results are subject to representation error and so
     may be platform-dependent.  Mathematically, the answer to ‘1 %/%
     0.2’ should be ‘5’, but because the IEC 60559 representation of
     ‘0.2’ is a binary fraction slightly larger than ‘0.2’ most
     platforms give ‘4’.

     Users are sometimes surprised by the value returned, for example
     why ‘(-8)^(1/3)’ is ‘NaN’.  For double inputs, R makes use of IEC
     60559 arithmetic on all platforms, together with the C system
     function ‘pow’ for the ‘^’ operator.  The relevant standards
     define the result in many corner cases.  In particular, the result
     in the example above is mandated by the C99 standard.  On many
     Unix-alike systems the command ‘man pow’ gives details of the
     values in a large number of corner cases.

     Arithmetic on type double in R is supposed to be done in ‘round to
     nearest, ties to even’ mode, but this does depend on the compiler
     and FPU being set up correctly.

_V_a_l_u_e:

     Unary ‘+’ and unary ‘-’ return a numeric or complex vector.  All
     attributes (including class) are preserved if there is no
     coercion: logical ‘x’ is coerced to integer and names, dims and
     dimnames are preserved.

     The binary operators return vectors containing the result of the
     element by element operations.  If involving a zero-length vector
     the result has length zero.  Otherwise, the elements of shorter
     vectors are recycled as necessary (with a ‘warning’ when they are
     recycled only _fractionally_).  The operators are ‘+’ for
     addition, ‘-’ for subtraction, ‘*’ for multiplication, ‘/’ for
     division and ‘^’ for exponentiation.

     ‘%%’ indicates ‘x mod y’ (“x modulo y”), i.e., computes the
     ‘remainder’ ‘r <- x %% y’, and ‘%/%’ indicates integer division,
     where R uses “floored” integer division, i.e., ‘q <- x %/% y :=
     floor(x/y)’, as promoted by Donald Knuth, see the Wikipedia page
     on ‘Modulo operation’, and hence ‘sign(r) == sign(y)’.  It is
     guaranteed that

     ‘ x == (x %% y) + y * (x %/% y) ’ (up to rounding error)

     unless ‘y == 0’ where the result of ‘%%’ is ‘NA_integer_’ or ‘NaN’
     (depending on the ‘typeof’ of the arguments) or for some
     non-finite arguments, e.g., when the RHS of the identity above
     amounts to ‘Inf - Inf’.

     If either argument is complex the result will be complex,
     otherwise if one or both arguments are numeric, the result will be
     numeric.  If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).

     The rules for determining the attributes of the result are rather
     complicated.  Most attributes are taken from the longer argument.
     Names will be copied from the first if it is the same length as
     the answer, otherwise from the second if that is.  If the
     arguments are the same length, attributes will be copied from
     both, with those of the first argument taking precedence when the
     same attribute is present in both arguments. For time series,
     these operations are allowed only if the series are compatible,
     when the class and ‘tsp’ attribute of whichever is a time series
     (the same, if both are) are used.  For arrays (and an array
     result) the dimensions and dimnames are taken from first argument
     if it is an array, otherwise the second.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Arith’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’ (with ‘e2’ missing for a unary operator).

_I_m_p_l_e_m_e_n_t_a_t_i_o_n _l_i_m_i_t_s:

     R is dependent on OS services (and they on FPUs) for
     floating-point arithmetic.  On all current R platforms IEC 60559
     (also known as IEEE 754) arithmetic is used, but some things in
     those standards are optional.  In particular, the support for
     _denormal_ aka _subnormal_ numbers (those outside the range given
     by ‘.Machine’) may differ between platforms and even between
     calculations on a single platform.

     Another potential issue is signed zeroes: on IEC 60559 platforms
     there are two zeroes with internal representations differing by
     sign.  Where possible R treats them as the same, but for example
     direct output from C code often does not do so and may output
     ‘-0.0’ (and on Windows whether it does so or not depends on the
     version of Windows).  One place in R where the difference might be
     seen is in division by zero: ‘1/x’ is ‘Inf’ or ‘-Inf’ depending on
     the sign of zero ‘x’.  Another place is ‘identical(0, -0, num.eq =
     FALSE)’.

_N_o_t_e:

     All logical operations involving a zero-length vector have a
     zero-length result.

     The binary operators are sometimes called as functions as e.g.
     ‘`&`(x, y)’: see the description of how argument-matching is done
     in ‘Ops’.

     ‘**’ is translated in the parser to ‘^’, but this was undocumented
     for many years.  It appears as an index entry in Becker et al.
     (1988), pointing to the help for ‘Deprecated’ but is not actually
     mentioned on that page.  Even though it had been deprecated in S
     for 20 years, it was still accepted in R in 2008.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     D. Goldberg (1991).  What Every Computer Scientist Should Know
     about Floating-Point Arithmetic.  _ACM Computing Surveys_,
     *23*(1), 5-48.  doi:10.1145/103162.103163
     <https://doi.org/10.1145/103162.103163>.

     Also available at
     <https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html>.

     For the IEC 60559 (aka IEEE 754) standard:
     <https://www.iso.org/standard/57469.html> and
     <https://en.wikipedia.org/wiki/IEEE_754>.

     On the integer division and remainder (modulo) computations, ‘%%’
     and ‘%/%’: <https://en.wikipedia.org/wiki/Modulo_operation>, and
     Donald Knuth (1972) _The Art of Computer Programming_, Vol.1.

_S_e_e _A_l_s_o:

     ‘sqrt’ for miscellaneous and ‘Special’ for special mathematical
     functions.

     ‘Syntax’ for operator precedence.

     ‘%*%’ for matrix multiplication.

_E_x_a_m_p_l_e_s:

     x <- -1:12
     x + 1
     2 * x + 3
     x %%  3 # is periodic  2 0  1  2 0  1 ...
     x %% -3 #  (ditto)    -1 0 -2 -1 0 -2 ...
     x %/% 5
     x %% Inf # now is defined by limit (gave NaN in earlier versions of R)

     ## Illustrating PR#18677, see above
     1 %/% print(0.2, digits=19)

`data()` will show which datasets R has obnoxiously polluted the global namespace with:

In [26]:
data()

Data sets in package ‘datasets’:

AirPassengers           Monthly Airline Passenger Numbers 1949-1960
BJsales                 Sales Data with Leading Indicator
BJsales.lead (BJsales)
                        Sales Data with Leading Indicator
BOD                     Biochemical Oxygen Demand
CO2                     Carbon Dioxide Uptake in Grass Plants
ChickWeight             Weight versus age of chicks on different diets
DNase                   Elisa assay of DNase
EuStockMarkets          Daily Closing Prices of Major European Stock
                        Indices, 1991-1998
Formaldehyde            Determination of Formaldehyde
HairEyeColor            Hair and Eye Color of Statistics Students
Harman23.cor            Harman Example 2.3
Harman74.cor            Harman Example 7.4
Indometh                Pharmacokinetics of Indomethacin
InsectSprays            Effectiveness of Insect Sprays
JohnsonJohnson          Quarterly Earnings per Johnson & Johnson Share
LakeHuron               Level of Lake Huron 1875-1972
LifeCycleSavings        Intercountry Life-Cycle Savings Data
Loblolly                Growth of Loblolly Pine Trees
Nile                    Flow of the River Nile
Orange                  Growth of Orange Trees
OrchardSprays           Potency of Orchard Sprays
PlantGrowth             Results from an Experiment on Plant Growth
Puromycin               Reaction Velocity of an Enzymatic Reaction
Seatbelts               Road Casualties in Great Britain 1969-84
Theoph                  Pharmacokinetics of Theophylline
Titanic                 Survival of passengers on the Titanic
ToothGrowth             The Effect of Vitamin C on Tooth Growth in
                        Guinea Pigs
UCBAdmissions           Student Admissions at UC Berkeley
UKDriverDeaths          Road Casualties in Great Britain 1969-84
UKgas                   UK Quarterly Gas Consumption
USAccDeaths             Accidental Deaths in the US 1973-1978
USArrests               Violent Crime Rates by US State
USJudgeRatings          Lawyers' Ratings of State Judges in the US
                        Superior Court
USPersonalExpenditure   Personal Expenditure Data
UScitiesD               Distances Between European Cities and Between
                        US Cities
VADeaths                Death Rates in Virginia (1940)
WWWusage                Internet Usage per Minute
WorldPhones             The World's Telephones
ability.cov             Ability and Intelligence Tests
airmiles                Passenger Miles on Commercial US Airlines,
                        1937-1960
airquality              New York Air Quality Measurements
anscombe                Anscombe's Quartet of 'Identical' Simple Linear
                        Regressions
attenu                  The Joyner-Boore Attenuation Data
attitude                The Chatterjee-Price Attitude Data
austres                 Quarterly Time Series of the Number of
                        Australian Residents
beaver1 (beavers)       Body Temperature Series of Two Beavers
beaver2 (beavers)       Body Temperature Series of Two Beavers
cars                    Speed and Stopping Distances of Cars
chickwts                Chicken Weights by Feed Type
co2                     Mauna Loa Atmospheric CO2 Concentration
crimtab                 Student's 3000 Criminals Data
discoveries             Yearly Numbers of Important Discoveries
esoph                   Smoking, Alcohol and (O)esophageal Cancer
euro                    Conversion Rates of Euro Currencies
euro.cross (euro)       Conversion Rates of Euro Currencies
eurodist                Distances Between European Cities and Between
                        US Cities
faithful                Old Faithful Geyser Data
fdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
freeny                  Freeny's Revenue Data
freeny.x (freeny)       Freeny's Revenue Data
freeny.y (freeny)       Freeny's Revenue Data
infert                  Infertility after Spontaneous and Induced
                        Abortion
iris                    Edgar Anderson's Iris Data
iris3                   Edgar Anderson's Iris Data
islands                 Areas of the World's Major Landmasses
ldeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
lh                      Luteinizing Hormone in Blood Samples
longley                 Longley's Economic Regression Data
lynx                    Annual Canadian Lynx trappings 1821-1934
mdeaths (UKLungDeaths)
                        Monthly Deaths from Lung Diseases in the UK
morley                  Michelson Speed of Light Data
mtcars                  Motor Trend Car Road Tests
nhtemp                  Average Yearly Temperatures in New Haven
nottem                  Average Monthly Temperatures at Nottingham,
                        1920-1939
npk                     Classical N, P, K Factorial Experiment
occupationalStatus      Occupational Status of Fathers and their Sons
precip                  Annual Precipitation in US Cities
presidents              Quarterly Approval Ratings of US Presidents
pressure                Vapor Pressure of Mercury as a Function of
                        Temperature
quakes                  Locations of Earthquakes off Fiji
randu                   Random Numbers from Congruential Generator
                        RANDU
rivers                  Lengths of Major North American Rivers
rock                    Measurements on Petroleum Rock Samples
sleep                   Student's Sleep Data
stack.loss (stackloss)
                        Brownlee's Stack Loss Plant Data
stack.x (stackloss)     Brownlee's Stack Loss Plant Data
stackloss               Brownlee's Stack Loss Plant Data
state.abb (state)       US State Facts and Figures
state.area (state)      US State Facts and Figures
state.center (state)    US State Facts and Figures
state.division (state)
                        US State Facts and Figures
state.name (state)      US State Facts and Figures
state.region (state)    US State Facts and Figures
state.x77 (state)       US State Facts and Figures
sunspot.month           Monthly Sunspot Data, from 1749 to "Present"
sunspot.year            Yearly Sunspot Data, 1700-1988
sunspots                Monthly Sunspot Numbers, 1749-1983
swiss                   Swiss Fertility and Socioeconomic Indicators
                        (1888) Data
treering                Yearly Tree-Ring Data, -6000-1979
trees                   Diameter, Height and Volume for Black Cherry
                        Trees
uspop                   Populations Recorded by the US Census
volcano                 Topographic Information on Auckland's Maunga
                        Whau Volcano
warpbreaks              The Number of Breaks in Yarn during Weaving
women                   Average Heights and Weights for American Women
Data sets in package ‘dslabs’:

admissions              Gender bias among graduate school admissions to
                        UC Berkeley.
brca                    Breast Cancer Wisconsin Diagnostic Dataset from
                        UCI Machine Learning Repository
brexit_polls            Brexit Poll Data
death_prob              2015 US Period Life Table
divorce_margarine       Divorce rate and margarine consumption data
gapminder               Gapminder Data
greenhouse_gases        Greenhouse gas concentrations over 2000 years
heights                 Self-reported Heights in Inches
historic_co2            Atmospheric carbon dioxide concentration over
                        800,000 years
mice_weights (mice_weigths)
                        Mice weights
mnist_127               Useful example for illustrating generative
                        models based on MNIST data
mnist_27                Useful example for illustrating machine
                        learning algorithms based on MNIST data
movielens               Movie ratings
murders                 US gun murders by state for 2010
na_example              Count data with some missing values
nyc_regents_scores      NYC Regents exams scores 2010
oecd (gapminder)        Gapminder Data
olive                   Italian olive
opec (gapminder)        Gapminder Data
outlier_example         Adult male heights in feet with outliers
polls_2008              Poll data for popular vote in 2008 presidential
                        election
polls_us_election_2016
                        Fivethirtyeight 2016 Poll Data
pr_death_counts (pr-death-counts)
                        Puerto Rico daily mortality
raw_data_research_funding_rates
                        Gender bias in research funding in the
                        Netherlands
reported_heights        Self-reported Heights
research_funding_rates
                        Gender bias in research funding in the
                        Netherlands
results_us_election_2012
                        2012 US presidential election results
results_us_election_2016 (polls_us_election_2016)
                        Fivethirtyeight 2016 Poll Data
sentiment_counts (trump_tweets)
                        Trump Tweets from2009 to 2017
stars                   Physical Properties of Stars
temp_carbon             Global temperature anomaly and carbon
                        emissions, 1751-2018
tissue_gene_expression
                        Gene expression profiles for 189 biological
                        samples taken from seven different tissue
                        types.
trump_tweets            Trump Tweets from2009 to 2017
us_contagious_diseases
                        Contagious disease data for US states

Use ‘data(package = .packages(all.available = TRUE))’
to list the data sets in all *available* packages.

Here is `co2`, for instance:

In [27]:
co2

     Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct
1959 315.42 316.31 316.50 317.56 318.13 318.00 316.39 314.65 313.68 313.18
1960 316.27 316.81 317.42 318.87 319.87 319.43 318.01 315.74 314.00 313.68
1961 316.73 317.54 318.38 319.31 320.42 319.61 318.42 316.63 314.83 315.16
1962 317.78 318.40 319.53 320.42 320.85 320.45 319.45 317.25 316.11 315.27
1963 318.58 318.92 319.70 321.22 322.08 321.31 319.58 317.61 316.05 315.83
1964 319.41 320.07 320.74 321.40 322.06 321.73 320.27 318.54 316.54 316.71
1965 319.27 320.28 320.73 321.97 322.00 321.71 321.05 318.71 317.66 317.14
1966 320.46 321.43 322.23 323.54 323.91 323.59 322.24 320.20 318.48 317.94
1967 322.17 322.34 322.88 324.25 324.83 323.93 322.38 320.76 319.10 319.24
1968 322.40 322.99 323.73 324.86 325.40 325.20 323.98 321.95 320.18 320.09
1969 323.83 324.26 325.47 326.50 327.21 326.54 325.72 323.50 322.22 321.62
1970 324.89 325.82 326.77 327.97 327.91 327.50 326.18 324.53 322.93 322.90
1971 326.01 326.51 327.01 327.62 328.76 328.40 327.20 325.27 323.20 323.40
1972 326.60 327.47 327.58 329.56 329.90 328.92 327.88 326.16 324.68 325.04
1973 328.37 329.40 330.14 331.33 332.31 331.90 330.70 329.15 327.35 327.02
1974 329.18 330.55 331.32 332.48 332.92 332.08 331.01 329.23 327.27 327.21
1975 330.23 331.25 331.87 333.14 333.80 333.43 331.73 329.90 328.40 328.17
1976 331.58 332.39 333.33 334.41 334.71 334.17 332.89 330.77 329.14 328.78
1977 332.75 333.24 334.53 335.90 336.57 336.10 334.76 332.59 331.42 330.98
1978 334.80 335.22 336.47 337.59 337.84 337.72 336.37 334.51 332.60 332.38
1979 336.05 336.59 337.79 338.71 339.30 339.12 337.56 335.92 333.75 333.70
1980 337.84 338.19 339.91 340.60 341.29 341.00 339.39 337.43 335.72 335.84
1981 339.06 340.30 341.21 342.33 342.74 342.08 340.32 338.26 336.52 336.68
1982 340.57 341.44 342.53 343.39 343.96 343.18 341.88 339.65 337.81 337.69
1983 341.20 342.35 342.93 344.77 345.58 345.14 343.81 342.21 339.69 339.82
1984 343.52 344.33 345.11 346.88 347.25 346.62 345.22 343.11 340.90 341.18
1985 344.79 345.82 347.25 348.17 348.74 348.07 346.38 344.51 342.92 342.62
1986 346.11 346.78 347.68 349.37 350.03 349.37 347.76 345.73 344.68 343.99
1987 347.84 348.29 349.23 350.80 351.66 351.07 349.33 347.92 346.27 346.18
1988 350.25 351.54 352.05 353.41 354.04 353.62 352.22 350.27 348.55 348.72
1989 352.60 352.92 353.53 355.26 355.52 354.97 353.75 351.52 349.64 349.83
1990 353.50 354.55 355.23 356.04 357.00 356.07 354.67 352.76 350.82 351.04
1991 354.59 355.63 357.03 358.48 359.22 358.12 356.06 353.92 352.05 352.11
1992 355.88 356.63 357.72 359.07 359.58 359.17 356.94 354.92 352.94 353.23
1993 356.63 357.10 358.32 359.41 360.23 359.55 357.53 355.48 353.67 353.95
1994 358.34 358.89 359.95 361.25 361.67 360.94 359.55 357.49 355.84 356.00
1995 359.98 361.03 361.66 363.48 363.82 363.30 361.94 359.50 358.11 357.80
1996 362.09 363.29 364.06 364.76 365.45 365.01 363.70 361.54 359.51 359.65
1997 363.23 364.06 364.61 366.40 366.84 365.68 364.52 362.57 360.24 360.83
     Nov    Dec
1959 314.66 315.43
1960 314.84 316.03
1961 315.94 316.85
1962 316.53 317.53
1963 316.91 318.20
1964 317.53 318.55
1965 318.70 319.25
1966 319.63 320.87
1967 320.56 321.80
1968 321.16 322.74
1969 322.69 323.95
1970 323.85 324.96
1971 324.63 325.85
1972 326.34 327.39
1973 327.99 328.48
1974 328.29 329.41
1975 329.32 330.59
1976 330.14 331.52
1977 332.24 333.68
1978 333.75 334.78
1979 335.12 336.56
1980 336.93 338.04
1981 338.19 339.44
1982 339.09 340.32
1983 340.98 342.82
1984 342.80 344.04
1985 344.06 345.38
1986 345.48 346.72
1987 347.64 348.78
1988 349.91 351.18
1989 351.14 352.37
1990 352.69 354.07
1991 353.64 354.89
1992 354.09 355.33
1993 355.30 356.78
1994 357.59 359.05
1995 359.61 360.74
1996 360.80 362.38
1997 362.49 364.34

Here are the class and type of `co2`, respectively:

In [28]:
class(co2)

[1] "ts"

In [29]:
typeof(co2)

[1] "double"

R features the mathematical constants $\pi$ and negative and positive $\infty$:

In [30]:
pi

[1] 3.141593

In [31]:
-Inf

[1] -Inf

In [32]:
Inf

[1] Inf

One can also get $e$ this way:

In [33]:
exp(1)

[1] 2.718282

Let's see how close R's base facilities can come to Euler's identity, $e^{i\pi} + 1 = 0$:

In [34]:
exp(sqrt(as.complex(-1)) * pi) + 1

[1] 0+1.224647e-16i

The result is indeed very close (but not identical) to 0.

The book later says not to save your workspace if you're using the R shell or RStudio. Just noting that here. Now for a few exercises.

**Exercise 1**: What is the sum of the first 100 positive integers? The formula for the sum of integers 1 through $n$ is $\frac{n(n+1)}{2}$. Define $n = 100$ and then use R to compute the sum of 1 through 100 using the formula. What is the sum?

I'll do a little better than that.

In [35]:
sum_of_positive_integers_from_1_to <- function(n) {
    n * (n + 1) / 2
}

sum_of_positive_integers_from_1_to(100)

[1] 5050

**Exercise 2**: Now use the same formula to compute the sum of the integers from 1 through 1000.

In [36]:
sum_of_positive_integers_from_1_to(1000)

[1] 500500

**Exercise 3**: Look at the result of typing the following code into R:

```r
n <- 1000
x <- seq(1, n)
sum(x)
```

Based on the result, what do you think the functions `seq()` and `sum()` do? You can use `help()`.

1. `sum()` creates a list of numbers and `seq()` adds them up.
2. `seq()` creates a list of numbers and `sum()` adds them up.
3. `seq()` creates a random list and `sum` computes the sum of 1 through 1,000.
4. `sum()` always returns the same number.

The answer is obviously #2.

**Exercise 4**: In math and programming, we say that we evaluate a function when we replace the argument with a given value. So if we type `sqrt(4)`, we evaluate the `sqrt()` function. In R, you can evaluate a function inside another function. The evaluations happen from the inside out. Use one line of code to compute the log, in base 10, of the square root of 100.

Easy; in fact I'll do a little better than that:

In [37]:
sqrt(100) |> log(base=10)

[1] 1

**Exercise 5**: Which of the following will always return the numeric value stored in `x`? You can try out examples and use the help system if you want.

1. `log(10^x)`
2. `log10(x^10)`
3. `log(exp(x))`
4. `exp(log(x, base = 2))`

Also easy:

In [38]:
seq(1, 100) |> exp() |> log()

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

The book mentions basics about object class that has been covered before. Briefly, here's another example:

In [39]:
class(42)

[1] "numeric"

Before going on to tibbles, the book then introduces an example of a `data.frame`, `murders`, from the `dslabs` package:

In [40]:
head(murders)

  state      abb region population total
1 Alabama    AL  South   4779736    135
2 Alaska     AK  West     710231     19
3 Arizona    AZ  West    6392017    232
4 Arkansas   AR  South   2915918     93
5 California CA  West   37253956   1257
6 Colorado   CO  West    5029196     65

In [41]:
class(murders)

[1] "data.frame"

The function `str()` (for "structure", not "string" and aforementioned `head()` are then shown:

In [42]:
str(murders)

'data.frame':	51 obs. of  5 variables:
 $ state     : chr  "Alabama" "Alaska" "Arizona" "Arkansas" ...
 $ abb       : chr  "AL" "AK" "AZ" "AR" ...
 $ region    : Factor w/ 4 levels "Northeast","South",..: 2 4 4 2 4 4 1 2 2 2 ...
 $ population: num  4779736 710231 6392017 2915918 37253956 ...
 $ total     : num  135 19 232 93 1257 ...

In [43]:
head(murders)

  state      abb region population total
1 Alabama    AL  South   4779736    135
2 Alaska     AK  West     710231     19
3 Arizona    AZ  West    6392017    232
4 Arkansas   AR  South   2915918     93
5 California CA  West   37253956   1257
6 Colorado   CO  West    5029196     65

Note that `head()` takes an optional argument `n` for the number of rows desired:

In [44]:
head(murders, n=20)

   state                abb region        population total
1  Alabama              AL  South          4779736    135
2  Alaska               AK  West            710231     19
3  Arizona              AZ  West           6392017    232
4  Arkansas             AR  South          2915918     93
5  California           CA  West          37253956   1257
6  Colorado             CO  West           5029196     65
7  Connecticut          CT  Northeast      3574097     97
8  Delaware             DE  South           897934     38
9  District of Columbia DC  South           601723     99
10 Florida              FL  South         19687653    669
11 Georgia              GA  South          9920000    376
12 Hawaii               HI  West           1360301      7
13 Idaho                ID  West           1567582     12
14 Illinois             IL  North Central 12830632    364
15 Indiana              IN  North Central  6483802    142
16 Iowa                 IA  North Central  3046355     21
17 Kansas               KS  North Central  2853118     63
18 Kentucky             KY  South          4339367    116
19 Louisiana            LA  South          4533372    351
20 Maine                ME  Northeast      1328361     11

Next the book goes into the `$` "extract" operator (see `` ?`$` ``). "For our analysis, we will need to access the different variables represented by columns included in this data frame. To do this, we use the accessor operator `$` in the following way:"

In [45]:
murders$population

 [1]  4779736   710231  6392017  2915918 37253956  5029196  3574097   897934
 [9]   601723 19687653  9920000  1360301  1567582 12830632  6483802  3046355
[17]  2853118  4339367  4533372  1328361  5773552  6547629  9883640  5303925
[25]  2967297  5988927   989415  1826341  2700551  1316470  8791894  2059179
[33] 19378102  9535483   672591 11536504  3751351  3831074 12702379  1052567
[41]  4625364   814180  6346105 25145561  2763885   625741  8001024  6724540
[49]  1852994  5686986   563626

Note that the extracted column is no longer a `data.frame`:

In [46]:
class(murders)

[1] "data.frame"

In [47]:
class(murders$population)

[1] "numeric"

`names()` can be used to get all the columns of a `data.frame` in order:

In [48]:
names(murders)

[1] "state"      "abb"        "region"     "population" "total"

The vectorized nature of R is then mentioned:

"The object `murders$population` is not one number but several. We call these types of objects vectors. A single number is technically a vector of length 1, but in general we use the term vectors to refer to objects with several entries."

In addition:

"In a `numeric` vector, every entry must be a number.

To store character strings, vectors can also be of class `character`. For example, the state names are characters:"

In [49]:
class(murders$state)

[1] "character"

What if there is a mix of `numeric` and `character` however? Coercion occurs to `character`:

In [50]:
coerced_vector <- c(1:3, 'foobar')
coerced_vector

[1] "1"      "2"      "3"      "foobar"

In [51]:
class(coerced_vector)

[1] "character"

"Another important type of vectors are logical vectors. These must be either `TRUE` or `FALSE`."

That is not entirely true; `NA` can also be present:

In [52]:
logical_vector_with_na <- c(TRUE, FALSE, NA)
logical_vector_with_na

[1]  TRUE FALSE    NA

In [53]:
class(logical_vector_with_na)

[1] "logical"

Indeed, come to think of it, other vectors can have `NA`:

In [54]:
integer_vector_with_na <- c(1:3, NA)
integer_vector_with_na

[1]  1  2  3 NA

In [55]:
class(integer_vector_with_na)

[1] "integer"

Side note: like in most other languages, `==` does an equality test of some kind and `=` does assignment, though it is preferred to do `<-` when not assigning values to function arguments, where `=` is required.

Other side note: [never use `T` or `F` instead of the reserved words `TRUE` and `FALSE`](https://www.r-bloggers.com/2012/12/r-tip-avoid-using-t-and-f-as-synonyms-for-true-and-false/).

Anyway, more documentation can be found on comparison operators with `?Comparison`:

In [56]:
?Comparison

Comparison                package:base                 R Documentation

_R_e_l_a_t_i_o_n_a_l _O_p_e_r_a_t_o_r_s

_D_e_s_c_r_i_p_t_i_o_n:

     Binary operators which allow the comparison of values in atomic
     vectors.

_U_s_a_g_e:

     x < y
     x > y
     x <= y
     x >= y
     x == y
     x != y

_A_r_g_u_m_e_n_t_s:

    x, y: atomic vectors, symbols, calls, or other objects for which
          methods have been written.

_D_e_t_a_i_l_s:

     The binary comparison operators are generic functions: methods can
     be written for them individually or via the ‘Ops’ group generic
     function.  (See ‘Ops’ for how dispatch is computed.)

     Comparison of strings in character vectors is lexicographic within
     the strings using the collating sequence of the locale in use: see
     ‘locales’.  The collating sequence of locales such as ‘en_US’ is
     normally different from ‘C’ (which should use ASCII) and can be
     surprising.  Beware of making _any_ assumptions about the
     collation order: e.g. in Estonian ‘Z’ comes between ‘S’ and ‘T’,
     and collation is not necessarily character-by-character - in
     Danish ‘aa’ sorts as a single letter, after ‘z’.  In Welsh ‘ng’
     may or may not be a single sorting unit: if it is it follows ‘g’.
     Some platforms may not respect the locale and always sort in
     numerical order of the bytes in an 8-bit locale, or in Unicode
     code-point order for a UTF-8 locale (and may not sort in the same
     order for the same language in different character sets).
     Collation of non-letters (spaces, punctuation signs, hyphens,
     fractions and so on) is even more problematic.

     Character strings can be compared with different marked encodings
     (see ‘Encoding’): they are translated to UTF-8 before comparison.

     Raw vectors should not really be considered to have an order, but
     the numeric order of the byte representation is used.

     At least one of ‘x’ and ‘y’ must be an atomic vector, but if the
     other is a list R attempts to coerce it to the type of the atomic
     vector: this will succeed if the list is made up of elements of
     length one that can be coerced to the correct type.

     If the two arguments are atomic vectors of different types, one is
     coerced to the type of the other, the (decreasing) order of
     precedence being character, complex, numeric, integer, logical and
     raw.

     Missing values (‘NA’) and ‘NaN’ values are regarded as
     non-comparable even to themselves, so comparisons involving them
     will always result in ‘NA’.  Missing values can also result when
     character strings are compared and one is not valid in the current
     collation locale.

     Language objects such as symbols and calls can only be used as
     operands for ‘==’ and ‘!=’; the other comparisons signal an error
     when one of the operands is a language object.  Currently language
     objects are deparsed to character strings before comparison. This
     can be inefficient and may not be what is really wanted. For
     equality comparisons ‘identical’ is usually a better choice.

_V_a_l_u_e:

     A logical vector indicating the result of the element by element
     comparison.  The elements of shorter vectors are recycled as
     necessary.

     Objects such as arrays or time-series can be compared this way
     provided they are conformable.

_S_4 _m_e_t_h_o_d_s:

     These operators are members of the S4 ‘Compare’ group generic, and
     so methods can be written for them individually as well as for the
     group generic (or the ‘Ops’ group generic), with arguments ‘c(e1,
     e2)’.

_N_o_t_e:

     Do not use ‘==’ and ‘!=’ for tests, such as in ‘if’ expressions,
     where you must get a single ‘TRUE’ or ‘FALSE’.  Unless you are
     absolutely sure that nothing unusual can happen, you should use
     the ‘identical’ function instead.

     For numerical and complex values, remember ‘==’ and ‘!=’ do not
     allow for the finite representation of fractions, nor for rounding
     error.  Using ‘all.equal’ with ‘identical’ or ‘isTRUE’ is almost
     always preferable; see the examples.  (This also applies to the
     other comparison operators.)

     These operators are sometimes called as functions as e.g. ‘`<`(x,
     y)’: see the description of how argument-matching is done in
     ‘Ops’.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Collation of character strings is a complex topic.  For an
     introduction see
     <https://en.wikipedia.org/wiki/Collating_sequence>.  The _Unicode
     Collation Algorithm_ (<https://unicode.org/reports/tr10/>) is
     likely to be increasingly influential.  Where available R by
     default makes use of ICU (<https://icu.unicode.org/>) for
     collation (except in a C locale).

_S_e_e _A_l_s_o:

     ‘Logic’ on how to _combine_ results of comparisons, i.e., logical
     vectors.

     ‘factor’ for the behaviour with factor arguments.

     ‘Syntax’ for operator precedence.

     ‘capabilities’ for whether ICU is available, and ‘icuSetCollate’
     to tune the string collation algorithm when it is.

_E_x_a_m_p_l_e_s:

     x <- stats::rnorm(20)
     x < 1
     x[x > 0]

     x1 <- 0.5 - 0.3
     x2 <- 0.3 - 0.1
     x1 == x2                   # FALSE on most machines
     isTRUE(all.equal(x1, x2))  # TRUE everywhere


     # range of most 8-bit charsets, as well as of Latin-1 in Unicode
     z <- c(32:126, 160:255)
     x <- if(l10n_info()$MBCS) {
         intToUtf8(z, multiple = TRUE)
     } else rawToChar(as.raw(z), multiple = TRUE)
     ## by number
     writeLines(strwrap(paste(x, collapse=" "), width = 60))
     ## by locale collation
     writeLines(strwrap(paste(sort(x), collapse=" "), width = 60))

The mention of `all.equal()` to allow for near equality with non-integers seems worth pointing out again:

In [57]:
0.5 - 0.3 == 0.3 - 0.1

[1] FALSE

In [58]:
all.equal(0.5 - 0.3, 0.3 - 0.1)

[1] TRUE

Indeed, what is the $\epsilon$ allowed by `all.equal()` by default?

In [59]:
?all.equal

all.equal                 package:base                 R Documentation

_T_e_s_t _i_f _T_w_o _O_b_j_e_c_t_s _a_r_e (_N_e_a_r_l_y) _E_q_u_a_l

_D_e_s_c_r_i_p_t_i_o_n:

     ‘all.equal(x, y)’ is a utility to compare R objects ‘x’ and ‘y’
     testing ‘near equality’.  If they are different, comparison is
     still made to some extent, and a report of the differences is
     returned.  Do not use ‘all.equal’ directly in ‘if’
     expressions-either use ‘isTRUE(all.equal(....))’ or ‘identical’ if
     appropriate.

_U_s_a_g_e:

     all.equal(target, current, ...)

     ## Default S3 method:
     all.equal(target, current, ..., check.class = TRUE)

     ## S3 method for class 'numeric'
     all.equal(target, current,
               tolerance = sqrt(.Machine$double.eps), scale = NULL,
               countEQ = FALSE,
               formatFUN = function(err, what) format(err),
               ..., check.attributes = TRUE, check.class = TRUE, giveErr = FALSE)

     ## S3 method for class 'list'
     all.equal(target, current, ...,
               check.attributes = TRUE, use.names = TRUE)

     ## S3 method for class 'environment'
     all.equal(target, current, all.names = TRUE,
               evaluate = TRUE, ...)

     ## S3 method for class 'function'
     all.equal(target, current, check.environment=TRUE, ...)

     ## S3 method for class 'POSIXt'
     all.equal(target, current, ..., tolerance = 1e-3, scale,
               check.tzone = TRUE)


     attr.all.equal(target, current, ...,
                    check.attributes = TRUE, check.names = TRUE)

_A_r_g_u_m_e_n_t_s:

  target: R object.

 current: other R object, to be compared with ‘target’.

     ...: further arguments for different methods, notably the
          following two, for numerical comparison:

tolerance: numeric >= 0.  Differences smaller than ‘tolerance’ are not
          reported.  The default value is close to ‘1.5e-8’.

   scale: ‘NULL’ or numeric > 0, typically of length 1 or
          ‘length(target)’.  See ‘Details’.

 countEQ: logical indicating if the ‘target == current’ cases should be
          counted when computing the mean (absolute or relative)
          differences.  The default, ‘FALSE’ may seem misleading in
          cases where ‘target’ and ‘current’ only differ in a few
          places; see the extensive example.

formatFUN: a ‘function’ of two arguments, ‘err’, the relative, absolute
          or scaled error, and ‘what’, a character string indicating
          the _kind_ of error; may be used, e.g., to format relative
          and absolute errors differently.

check.attributes: logical indicating if the ‘attributes’ of ‘target’
          and ‘current’ (other than the names) should be compared.

check.class: logical indicating if the ‘data.class()’ of ‘target’ and
          ‘current’ should be compared.

 giveErr: ‘logical’ indicating if the result should contain the
          numerical error as an ‘"err"’ attribute.

use.names: logical indicating if ‘list’ comparison should report
          differing components by name (if matching) instead of integer
          index.  Note that this comes after ‘...’ and so must be
          specified by its full name.

all.names: logical passed to ‘ls’ indicating if “hidden” objects should
          also be considered in the environments.

evaluate: for the ‘environment’ method: ‘logical’ indicating if
          “promises should be forced”, i.e., typically formal function
          arguments be evaluated for comparison.  If false, only the
          ‘names’ of the objects in the two environments are checked
          for equality.

check.environment: logical requiring that the ‘environment()’s of
          functions should be compared, too.  You may need to set
          ‘check.environment=FALSE’ in unexpected cases, such as when
          comparing two ‘nls()’ fits.

check.tzone: logical indicating if the ‘"tzone"’ attributes of ‘target’
          and ‘current’ should be compared.

check.names: logical indicating if the ‘names(.)’ of ‘target’ and
          ‘current’ should be compared.

_D_e_t_a_i_l_s:

     ‘all.equal’ is a generic function, dispatching methods on the
     ‘target’ argument.  To see the available methods, use
     ‘methods("all.equal")’, but note that the default method also does
     some dispatching, e.g. using the raw method for logical targets.

     Remember that arguments which follow ‘...’ must be specified by
     (unabbreviated) name.  It is inadvisable to pass unnamed arguments
     in ‘...’ as these will match different arguments in different
     methods.

     Numerical comparisons for ‘scale = NULL’ (the default) are
     typically on a _relative difference_ scale unless the ‘target’
     values are close to zero or infinite. Specifically, the scale is
     computed as the mean absolute value of ‘target’.  If this scale is
     finite and exceeds ‘tolerance’, differences are expressed relative
     to it; otherwise, absolute differences are used.  Note that this
     scale and all further steps are computed only for those vector
     elements where ‘target’ is not ‘NA’ and differs from ‘current’.
     If ‘countEQ’ is true, the equal and ‘NA’ cases are _counted_ in
     determining the “sample” size.

     If ‘scale’ is numeric (and positive), absolute comparisons are
     made after scaling (dividing) by ‘scale’.  Note that if all of
     scale is close to 1 (specifically, within 1e-7), the difference is
     still reported as being on an absolute scale.

     For complex ‘target’, the modulus (‘Mod’) of the difference is
     used: ‘all.equal.numeric’ is called so arguments ‘tolerance’ and
     ‘scale’ are available.

     The ‘list’ method compares components of ‘target’ and ‘current’
     recursively, passing all other arguments, as long as both are
     “list-like”, i.e., fulfill either ‘is.vector’ or ‘is.list’.

     The ‘environment’ method works via the ‘list’ method, and is also
     used for reference classes (unless a specific ‘all.equal’ method
     is defined).

     The method for date-time objects uses ‘all.equal.numeric’ to
     compare times (in ‘"POSIXct"’ representation) with a default
     ‘tolerance’ of 0.001 seconds, ignoring ‘scale’.  A time zone
     mismatch between ‘target’ and ‘current’ is reported unless
     ‘check.tzone = FALSE’.

     ‘attr.all.equal’ is used for comparing ‘attributes’, returning
     ‘NULL’ or a ‘character’ vector.

_V_a_l_u_e:

     Either ‘TRUE’ (‘NULL’ for ‘attr.all.equal’) or a vector of ‘mode’
     ‘"character"’ describing the differences between ‘target’ and
     ‘current’.

_R_e_f_e_r_e_n_c_e_s:

     Chambers, J. M. (1998) _Programming with Data. A Guide to the S
     Language_.  Springer (for ‘=’).

_S_e_e _A_l_s_o:

     ‘identical’, ‘isTRUE’, ‘==’, and ‘all’ for exact equality testing.

_E_x_a_m_p_l_e_s:

     all.equal(pi, 355/113)
     # not precise enough (default tol) > relative error

     quarts <- 1/4 + 1:10 # exact
     d45 <- pi*quarts ; one <- rep(1, 10)
     tan(d45) == one  # mostly FALSE, as typically exact; embarrassingly,
     tanpi(quarts) == one # (is always FALSE (Fedora 34; gcc 11.2.1))
     stopifnot(all.equal(
               tan(d45), one)) # TRUE, but not if we are picky:
     all.equal(tan(d45), one, tolerance = 0)  # to see difference
     all.equal(tan(d45), one, tolerance = 0, scale = 1)# "absolute diff.."
     all.equal(tan(d45), one, tolerance = 0, scale = 1+(-2:2)/1e9) # "absolute"
     all.equal(tan(d45), one, tolerance = 0, scale = 1+(-2:2)/1e6) # "scaled"

     ## advanced: equality of environments
     ae <- all.equal(as.environment("package:stats"),
                     asNamespace("stats"))
     stopifnot(is.character(ae), length(ae) > 10,
               ## were incorrectly "considered equal" in R <= 3.1.1
               all.equal(asNamespace("stats"), asNamespace("stats")))

     ## A situation where  'countEQ = TRUE' makes sense:
     x1 <- x2 <- (1:100)/10;  x2[2] <- 1.1*x1[2]
     ## 99 out of 100 pairs (x1[i], x2[i]) are equal:
     plot(x1,x2, main = "all.equal.numeric() -- not counting equal parts")
     all.equal(x1,x2) ## "Mean relative difference: 0.1"
     mtext(paste("all.equal(x1,x2) :", all.equal(x1,x2)), line= -2)
     ##' extract the 'Mean relative difference' as number:
     all.eqNum <- function(...) as.numeric(sub(".*:", '', all.equal(...)))
     set.seed(17)
     ## When x2 is jittered, typically all pairs (x1[i],x2[i]) do differ:
     summary(r <- replicate(100, all.eqNum(x1, x2*(1+rnorm(x1)*1e-7))))
     mtext(paste("mean(all.equal(x1, x2*(1 + eps_k))) {100 x} Mean rel.diff.=",
                 signif(mean(r), 3)), line = -4, adj=0)
     ## With argument  countEQ=TRUE, get "the same" (w/o need for jittering):
     mtext(paste("all.equal(x1,x2, countEQ=TRUE) :",
               signif(all.eqNum(x1,x2, countEQ=TRUE), 3)), line= -6, col=2)

     ## Using giveErr=TRUE :
     x1. <- x1 * (1+ 1e-9*rnorm(x1))
     str(all.equal(x1, x1., giveErr=TRUE))
     ## logi TRUE
     ## - attr(*,  "err")= num 8.66e-10
     ## - attr(*, "what")= chr "relative"

     ## Used with stopifnot(), still *showing* diff:
     all.equalShow <- function (...) {
        r <- all.equal(..., giveErr=TRUE)
        cat(attr(r,"what"), "err:", attr(r,"err"), "\n")
        c(r) # can drop attributes, as not used anymore
     }
     # checks, showing error in any case:
     stopifnot(all.equalShow(x1, x1.)) # -> relative err: 8.66002e-10
     tryCatch(error=identity, stopifnot(all.equalShow(x1, 2*x1))) -> eAe
     stopifnot(inherits(eAe, "error"))
     # stopifnot(all.equal....()) giving smart msg:
     cat(conditionMessage(eAe), "\n")

     two <- structure(2, foo = 1, class = "bar")
     all.equal(two^20, 2^20) # lots of diff
     all.equal(two^20, 2^20, check.attributes = FALSE)# "target is bar, current is numeric"
     all.equal(two^20, 2^20, check.attributes = FALSE, check.class = FALSE) # TRUE

     ## comparison of date-time objects
     now <- Sys.time()
     stopifnot(
     all.equal(now, now + 1e-4)  # TRUE (default tolerance = 0.001 seconds)
     )
     all.equal(now, now + 0.2)
     all.equal(now, as.POSIXlt(now, "UTC"))
     stopifnot(
     all.equal(now, as.POSIXlt(now, "UTC"), check.tzone = FALSE)  # TRUE
     )

Here it is given by `sqrt(.Machine$double.eps)`:

In [60]:
sqrt(.Machine$double.eps)

[1] 1.490116e-08

Another important caveat appears: "\[B\]y default, numbers are assigned class `numeric` even when they are round integers. For example, `class(1)` returns `numeric`. You can turn them into class `integer` with the `as.integer()` function or by adding an `L` like this: `1L`. Note the class by typing: `class(1L)`."

In [61]:
class(1L)

[1] "integer"

`murders$region` looks like it has the class `character`, but it does not:

In [62]:
class(murders$region)

[1] "factor"

`factor`s are for categorical data and they look like character strings, but under the hood R assigns them to distinct integers in order to be more efficient. These coded categories can be seen with the `levels()` function:

In [63]:
levels(murders$region)

[1] "Northeast"     "South"         "North Central" "West"

I'm going to crib a good deal from the book here:

"Note that the levels have an order that is different from the order of appearance in the `factor` object. The default in R is for the levels to follow alphabetical order. However, often we want the levels to follow a different order. You can specify an order through the `levels` argument when creating the `factor` with the `factor()` function. For example, in the `murders` dataset regions are ordered from east to west. The function `reorder()` lets us change the order of the levels of a `factor` variable based on a summary computed on a `numeric` vector."

\[There are a number of ways to specify ordinal `factor`s but let's just look at this one for now.\]

"Suppose we want the levels of `region` ordered by the total number of murders rather than alphabetically. If there are values associated with each level, we can use the `reorder()` function and specify a data summary to determine the order. The following code takes the sum of the total murders in each region, and reorders the `factor` following these sums."

In [64]:
region <- murders$region
value <- murders$total
region <- reorder(region, value, FUN = sum)
levels(region)

[1] "Northeast"     "North Central" "West"          "South"

The book then warns: "`factor`s can be a source of confusion since sometimes they behave like `character`s and sometimes they do not. As a result, confusing `factor`s and `character`s are a common source of bugs."

After said warning, the book starts to go into `list`s and how `data.frame`s are a special case of `list`s. I don't know enough about R—which does not have a conventional object system—to confirm that this is indeed the case but I was able to find independent confirmation elsewhere so let's roll with it. Anyway, `list`s are useful because each member can have a different type. Here is an example of a `list` (`c()` has been used earlier but will also be mentioned a bit later):

In [65]:
record <- list(name = 'John Doe',
               student_id = 1234,
               grades = c(95, 82, 91, 97, 93),
               final_grade = 'A')
record

$name
[1] "John Doe"

$student_id
[1] 1234

$grades
[1] 95 82 91 97 93

$final_grade
[1] "A"

`$` can be used to extract elements of a `list`, as with `data.frame`s:

In [66]:
record$student_id

[1] 1234

The double bracket notation (`[[...]]`) with a `character` object also works:

In [67]:
record[['student_id']]

[1] 1234

Annoyingly, though maybe it will be covered later, the book doesn't say *why* the more cumbersome notation has an advantage: it can work with any `character` object and not just a field specified at the time of writing by the author of a program:

In [68]:
# Substituting a more involved process of computing the field for demonstration purposes
field_that_could_be_anything <- 'student_id'
record[[field_that_could_be_anything]]

[1] 1234

Lists do not require fields to be named:

In [69]:
record2 <- list('John Doe', 1234)
record2

[[1]]
[1] "John Doe"

[[2]]
[1] 1234

Two things have to be noted here:

1. R in opposition to most programming languages uses 1-based indexing rather than 0-based indexing.
2. `$` does not work with accessing these numerical fields; double brackets are necessary.

In [70]:
record2[[1]]

[1] "John Doe"

The book briefly comments on `matrix` objects. The reason the corresponding section is so brief is because, typically, one will be working most directly with `data.frame` or `tibble` objects. `matrix` operations are important "under the hood" though. The indexing operations on `matrix` objects that will be shown are shared in common with the other two mentioned classes of objects. Here's a `matrix` (`:` will be explained fully a bit later):

In [71]:
mat <- matrix(1:12, 4, 3)
mat

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

Here's how to access a single cell of a `matrix`, with row number first (1-based, remember) and column number second:

In [72]:
mat[2, 3]

[1] 10

Here's how to get an entire row:

In [73]:
mat[2, ]

[1]  2  6 10

Note that the row in question is no longer a `matrix`:

In [74]:
class(mat[2, ])

[1] "integer"

Columns can also be extracted in the same fashion:

In [75]:
mat[, 3]

[1]  9 10 11 12

How about getting subsets of a `matrix` object that are themselves `matrix` objects? Here's one example:

In [76]:
mat[, 2:3]

     [,1] [,2]
[1,] 5     9
[2,] 6    10
[3,] 7    11
[4,] 8    12

Here's another one:

In [77]:
mat[1:2, 2:3]

     [,1] [,2]
[1,] 5     9
[2,] 6    10

It is even possible to turn a `matrix` into a `data.frame` using `as.data.frame()`:

In [78]:
as.data.frame(mat)

  V1 V2 V3
1 1  5   9
2 2  6  10
3 3  7  11
4 4  8  12

The operations described above also work on `data.frame` objects:

In [79]:
murders[25, 1]

[1] "Mississippi"

In [80]:
murders[2:3, ]

  state   abb region population total
2 Alaska  AK  West    710231     19
3 Arizona AZ  West   6392017    232

Now for a few more exercises.

**Exercise 6**: Make sure the US `murders` dataset is loaded. Use the function `str()` to examine the structure of the `murders` object. Which of the following best describes the variables represented in this `data.frame`?

1. The 51 states.
2. The murder rates for all 50 states and DC.
3. The state name, the abbreviation of the state name, the state's region, and the state's population and total number of murders for 2010.
4. `str()` shows no relevant information.

In [81]:
str(murders)

'data.frame':	51 obs. of  5 variables:
 $ state     : chr  "Alabama" "Alaska" "Arizona" "Arkansas" ...
 $ abb       : chr  "AL" "AK" "AZ" "AR" ...
 $ region    : Factor w/ 4 levels "Northeast","South",..: 2 4 4 2 4 4 1 2 2 2 ...
 $ population: num  4779736 710231 6392017 2915918 37253956 ...
 $ total     : num  135 19 232 93 1257 ...

Clearly the answer is #3.

**Exercise 7**: What are the column names used by the data frame for these five variables?

In [82]:
names(murders)

[1] "state"      "abb"        "region"     "population" "total"

**Exercise 8**: Use the accessor `$` to extract the state abbreviations and assign them to the variable `a`. What is the class of this object?

In [83]:
a <- murders$abb
class(a)

[1] "character"

**Exercise 9**: Now use the square brackets to extract the state abbreviations and assign them to the variable `b`. Use the identical function to determine if `a` and `b` are the same.

In [84]:
b <- murders[['abb']]
identical(a, b)

[1] TRUE

**Exercise 10**: We saw that the region column stores a `factor`. You can corroborate this by typing:

```r
class(murders$region)
```

With one line of code, use the functions `levels()` and `length()` to determine the number of regions defined by this dataset.

In [85]:
levels(murders$region) |> length()

[1] 4

**Exercise 11**: The function `table()` takes a vector and returns the frequency of each element. You can quickly see how many states are in each region by applying this function. Use this function in one line of code to create a table of number of states per region.

In [86]:
table(murders$region)

    Northeast         South North Central          West
            9            17            12            13

Now it's time to shed a little more light on vectors. From the book:

"In R, the most basic objects available to store data are vectors. As we have seen, complex datasets can usually be broken down into components that are vectors. For example, in a `data.frame`, each column is a vector. Here we learn more about this important class."

Here's an integer vector created with the function `c()` (which stands for "concatenate"):

In [87]:
codes <- c(380, 124, 818)
codes

[1] 380 124 818

Character vectors are also possible (double quotes would have also worked):

In [88]:
country <- c('italy', 'canada', 'egypt')
country

[1] "italy"  "canada" "egypt"

Elements of a vector can be named:

In [89]:
codes <- c(italy = 380, canada = 124, egypt = 818)
codes

 italy canada  egypt
   380    124    818

The class of `codes` remains `numeric`:

In [90]:
class(codes)

[1] "numeric"

`names()` works on such a vector:

In [91]:
names(codes)

[1] "italy"  "canada" "egypt"

The following also works:

In [92]:
codes <- c("italy" = 380, "canada" = 124, "egypt" = 818)
codes

 italy canada  egypt
   380    124    818

`names()` also works as what's called a "replacement function", specifically called `names()<-`:

In [93]:
codes <- c(380, 124, 818)
country <- c('italy', 'canada', 'egypt')
names(codes) <- country
codes

 italy canada  egypt
   380    124    818

Now enter `seq()` which is a bit like `range()` in Python. Here's an example of the default behavior with only two arguments:

In [94]:
seq(1, 10)

 [1]  1  2  3  4  5  6  7  8  9 10

An optional argument, `by`, has the default value of 1 but can be overridden:

In [95]:
seq(1, 10, 2)

[1] 1 3 5 7 9

The default behavior can be expressed more concisely using `:`:

In [96]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

Remember that `:` is really a function:

In [97]:
`:`(1, 10)

 [1]  1  2  3  4  5  6  7  8  9 10

A sequence produced with `seq()`, if it contains only `integer`s, will have the corresponding class:

In [98]:
class(1:10)

[1] "integer"

Anything other than `integer`s will make it `numeric`:

In [99]:
class(seq(1, 10, 0.5))

[1] "numeric"

In [100]:
codes

 italy canada  egypt
   380    124    818

Here are some examples of accessing vectors, starting with the very basic access of a single element (and remember: 1-based indexing):

In [101]:
codes[2]

canada
   124

Here's an example of subsetting two elements and note that they do not need to be contiguous!

In [102]:
codes[c(1, 3)]

italy egypt
  380   818

Here it becomes possible to do something like Python list slicing:

In [103]:
codes[1:2]

 italy canada
   380    124

Names, if present, can also be used:

In [104]:
codes['canada']

canada
   124

Here the elements are even accessed in backwards order!

In [105]:
codes[c('egypt', 'italy')]

egypt italy
  818   380

Now it's time for coercion. Somewhat like JavaScript (unfortunately), R will silently coerce a whole vector to `character`:

In [106]:
x <- c(1, 'canada', 3)
x

[1] "1"      "canada" "3"

In [107]:
class(x)

[1] "character"

Explicit coercion can also be done, for example:

In [108]:
x <- 1:5
y <- as.character(x)
y

[1] "1" "2" "3" "4" "5"

`as.numeric()`, seen below, can be quite useful because many raw datasets that need to be cleaned before further analysis will contain numbers as character strings:

In [109]:
as.numeric(y)

[1] 1 2 3 4 5

The book didn't cover it (yet) but there's also an `as.logical()` function that, at least with `integer` and `numeric` data, recognizes anything other than 0 as `TRUE`:

In [110]:
as.logical(c(-1, 0, 0.2, 1, 2, 3))

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE

When applied to `character` data, `as.logical()` will convert the strings `'TRUE'` and `'FALSE'` ([as well as a few others](https://stackoverflow.com/a/79464184/2663150)) to `TRUE` and `FALSE` and everything else to `NA` (stands for "not available"):

In [111]:
as.logical(c('TRUE', 'True', 'true', 'FALSE', 'False', 'false', 'foobar'))

[1]  TRUE  TRUE  TRUE FALSE FALSE FALSE    NA

The book gives further rationale for the existence of `NA`:

"When a function tries to coerce one type to another and encounters an impossible case, it usually gives us a warning and turns the entry into a special value called an `NA` for 'not available'. For example:"

In [112]:
x <- c('1', 'b', '3')
as.numeric(x)

Warning message:
“NAs introduced by coercion”

[1]  1 NA  3

"R does not have any guesses for what number you want when you type `'b'`, so it does not try.

As a data scientist you will encounter the `NA`s often as they are generally used for missing data, a common problem in real-world datasets."

Now for some exercises again.

**Exercise 12**: Use the function `c()` to create a vector with the average high temperatures in January for Beijing, Lagos, Paris, Rio de Janeiro, San Juan, and Toronto, which are 35, 88, 42, 84, 81, and 30 degrees Fahrenheit. Call the object `temp`:

In [113]:
temp <- c(35, 88, 42, 84, 81, 30)
temp

[1] 35 88 42 84 81 30

**Exercise 13**: Now create a vector with the city names and call the object `city`.

In [114]:
city <- c('Beijing', 'Lagos', 'Paris', 'Rio de Jainero', 'San Juan', 'Toronto')
city

[1] "Beijing"        "Lagos"          "Paris"          "Rio de Jainero"
[5] "San Juan"       "Toronto"

**Exercise 14**: Use the `names()` function and the objects defined in the previous exercises to associate the temperature data with its corresponding city.

In [115]:
names(temp) <- city
temp

       Beijing          Lagos          Paris Rio de Jainero       San Juan
            35             88             42             84             81
       Toronto
            30

**Exercise 15**: Use the `[` and `:` operators to access the temperature of the first three cities on the list.

In [116]:
temp[1:3]

Beijing   Lagos   Paris
     35      88      42

**Exercise 16**: Use the `[` operator to access the temperature of Paris and San Juan.

In [117]:
temp[c('Paris', 'San Juan')]

   Paris San Juan
      42       81

**Exercise 17**: Use the `:` operator to create a sequence of numbers $12, 13, 14, \ldots, 73$.

In [118]:
12:73

 [1] 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
[26] 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61
[51] 62 63 64 65 66 67 68 69 70 71 72 73

**Exercise 18**: Create a vector containing all the positive odd numbers smaller than 100.

In [119]:
seq(1, 100, 2)

 [1]  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
[26] 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

**Exercise 19**: Create a vector of numbers that starts at 6, does not pass 55, and adds numbers in increments of $\frac{4}{7}$: 6, 6 + $\frac{4}{7}$, 6 + $\frac{8}{7}$, and so on. How many numbers does the list have? Hint: use `seq()` and `length()`.

In [120]:
vector_for_ex_19 <- seq(6, 55, 4/7)
vector_for_ex_19

 [1]  6.000000  6.571429  7.142857  7.714286  8.285714  8.857143  9.428571
 [8] 10.000000 10.571429 11.142857 11.714286 12.285714 12.857143 13.428571
[15] 14.000000 14.571429 15.142857 15.714286 16.285714 16.857143 17.428571
[22] 18.000000 18.571429 19.142857 19.714286 20.285714 20.857143 21.428571
[29] 22.000000 22.571429 23.142857 23.714286 24.285714 24.857143 25.428571
[36] 26.000000 26.571429 27.142857 27.714286 28.285714 28.857143 29.428571
[43] 30.000000 30.571429 31.142857 31.714286 32.285714 32.857143 33.428571
[50] 34.000000 34.571429 35.142857 35.714286 36.285714 36.857143 37.428571
[57] 38.000000 38.571429 39.142857 39.714286 40.285714 40.857143 41.428571
[64] 42.000000 42.571429 43.142857 43.714286 44.285714 44.857143 45.428571
[71] 46.000000 46.571429 47.142857 47.714286 48.285714 48.857143 49.428571
[78] 50.000000 50.571429 51.142857 51.714286 52.285714 52.857143 53.428571
[85] 54.000000 54.571429

In [121]:
length(vector_for_ex_19)

[1] 86

**Exercise 20**: What is the class of the following object `a <- seq(1, 10, 0.5)`?

In [122]:
a <- seq(1, 10, 0.5)
class(a)

[1] "numeric"

**Exercise 21**: What is the class of the following object `a <- seq(1, 10)`?

In [123]:
a <- seq(1, 10)
class(a)

[1] "integer"

**Exercise 22**: The class of `class(a <- 1)` is `numeric`, not `integer`. R defaults to `numeric` and to force an `integer`, you need to add the letter `L`. Confirm that the class of `1L` is `integer`.

In [124]:
class(a <- 1)

[1] "numeric"

In [125]:
class(1L)

[1] "integer"

**Exercise 23**: Define the following vector:

```r
x <- c('1', '3', '5')
```

and coerce it to get integers.

In [1]:
x <- c('1', '3', '5')
as.integer(x)

[1] 1 3 5